# Guild-specific Config file

guild:
    id: ~
    invite: ~

bot:
    prefix: ~

ext:
    adv_replies: ~
    danked_memer: ~
    messagehook: ~
    reactomatic: ~
    welcomer:
        welcome_channel: ~
