# Global Config file
# YAML format
# Configs independent of guilds


bot:
    prefix: '-BotCord '              # prefix that works everywhere
    reply_to_mentions: true          # whether mentioning the bot is a valid prefix
    ignore_self: false               # if true, actions from the bot itself not trigger commands
    message_cache: 10000             # how many messages to keep in the client-side cache
    intents: all                     # todo: changed intents based on this setting
    extension_dir: 'extensions'      # the name of the folder (under the working directory) that contains all the extension packages

permissions:
    owner:
        - ~

    admin:
        - ~

    mod:
        - ~

log_channels:
    debug: ~
    info: ~
    error: ~
