#file: noinspection SpellCheckingInspection
roasts:
  - please leave the server.
  - must be feeling extremely insecure right now
  - stinks.
  - was a mistake
  - wasn't meant to happen
  - '"hey, you are adopted"'
  - hi neek, please kindly stfu
  - "'s face makes onions cry"
  - pulls the class average down
  - likes to eat copper oxide
  - ', hi braceface'
  - is the reason the gene pool needs a lifeguard
  - is rowansexual
  - doesn't know how to commit sudoku
  - If laughter is the best medicine, your face would stop COVID in 3 hours
  - if i had a face and brain like yours, i'd sue my parents
  - You must have been born on a highway cos' that's where most accidents happen
  - quillbots their essays and gets 28/30
  - doesn't respect THE SocietyBot
  - fuck off
  - You are as useless as the "ueue" in "queue"
  - has something in their chin.... no, the 5th one down
  - has got no friends
  - PROFESSIONAL STOCK GURU, DAILY EARNINGS -$700K
  - is a nerd but happens to be dumber than everyone else
  - Sounds like a You problem.
  - https://cdn.discordapp.com/attachments/859712351821103104/891274889888170025/10_million_million_million_million.mp4
  - hey, you have your entire life to be an idiot, so why not take today off
  - Hello know-it-all, do you know when you should shut the fuck up?
  - "'s birth certificate is actually an apology letter from the condom factory"
  - get good lol.
  - OH MY FUCKING GOD, YOU SPEAK!!!!
