# Guild-specific Config file

guild:
    id: 770493700883087361
    invite: https://discord.gg/QU6Wk2Bn
    name: society

bot:
    prefix: '*'

ext:
    welcomer:
        enabled: true
        welcome_channel: 859712351821103104
