# Guild-specific Config file

guild:
    id: 770493700883087361
    invite:
    name: society


bot:
    prefix: '*'


ext:
    welcomer:
        enabled: true
        welcome_channel: 859712351821103104
    adv_replies:
        enabled: true
    colorroles:
        enabled: true
    danked_memer:
        enabled: true
    messagehook:
        enabled: true
    mod_utils:
        enabled: true
    nerd_utils:
        enabled: true
    reactomatic:
        enabled: true
