# Guild-specific Config file

guild:
    id: 839457899360157706
    invite:
    name: Myself


bot:
    prefix:

ext:
    adv_replies:
        enabled: true
    colorroles:
        enabled: true
    danked_memer:
        enabled: true
    messagehook:
        enabled: true
    mod_utils:
        enabled: true
    nerd_utils:
        enabled: true
    reactomatic:
        enabled: true
    welcomer:
        enabled: true
