# Guild-specific Config file

guild:
    id: 839457899360157706
    invite:
    name: Myself


bot:
    prefix:

ext:
    adv_replies:
        enabled: false
    colorroles:
        enabled: false
    danked_memer:
        enabled: false
    messagehook:
        enabled: false
    mod_utils:
        enabled: false
    nerd_utils:
        enabled: false
    reactomatic:
        enabled: false
    welcomer:
        enabled: false
