# Guild-specific Config file

guild:
    id: 888009787810402324
    invite: https://discord.gg/ArdRypUb3M
    name: the hood


bot:
    prefix:

ext:
    welcomer:
        enabled: true
        welcome_channel: 888009787810402327
    adv_replies:
        enabled: true
    colorroles:
        enabled: true
    danked_memer:
        enabled: true
    messagehook:
        enabled: true
    mod_utils:
        enabled: true
    nerd_utils:
        enabled: true
    reactomatic:
        enabled: true
